import React, { createContext, useState, useEffect, ReactNode } from 'react';

const translations = {
  en: {
    signIn: 'Sign in',
    welcomeBack: 'Welcome back',
    dashboard: 'Dashboard',
    accounts: 'Accounts',
    cards: 'Cards',
    notifications: 'Notifications',
    settings: 'Settings',
    transfer: 'Transfer',
    cardPayment: 'Card payment',
    transactions: 'Transactions',
    scheduled: 'Scheduled',
    openAccount: 'Open account',
    current: 'Current',
    savings: 'Savings',
    business: 'Business',
    available: 'Available',
    blocked: 'Blocked',
    total: 'Total',
    from: 'From',
    to: 'To',
    amount: 'Amount',
    description: 'Description',
    cancel: 'Cancel',
    save: 'Save',
    loading: 'Loading…',
    tryAgain: 'Try again',
    noAccountsYet: 'No accounts yet',
    noCardsYet: 'No cards yet',
    noTxnsYet: 'No transactions yet',
    markAllRead: 'Mark all read',
    freeze: 'Freeze account',
    close: 'Close account',
    blockCard: 'Block card',
    terminate: 'Terminate',
    saveChanges: 'Save changes',
    issueCard: 'Issue a card',
    signOut: 'Sign out',
    profile: 'Profile',
    language: 'Language',
    sessions: 'Sessions',
    password: 'Password',
    username: 'Username',
    email: 'Email',
    phone: 'Phone',
    firstName: 'First name',
    secondName: 'Middle name',
    thirdName: 'Last name',
    egn: 'EGN',
    birthDate: 'Birth date',
    register: 'Create account',
    confirmPassword: 'Confirm password',
    security: 'Security',
    twoFA: 'Two-factor authentication',
    enable: 'Enable',
    disable: 'Disable',
    admin: 'Admin',
    send: 'Send',
    broadcast: 'Broadcast',
    bulk: 'Bulk send',
    users: 'Users',
    role: 'Role',
    frequency: 'Frequency',
    once: 'Once',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    newScheduled: 'New scheduled payment',
    cardType: 'Card type',
    debit: 'Debit',
    credit: 'Credit',
    virtual: 'Virtual',
    limits: 'Spending limits',
    dailyLimit: 'Daily limit',
    monthlyLimit: 'Monthly limit',
    singleLimit: 'Single transaction',
    branch: 'Branch',
    currency: 'Currency',
    balance: 'Balance',
    iban: 'IBAN',
    status: 'Status',
    type: 'Type',
    date: 'Date',
    reference: 'Reference',
    merchant: 'Merchant',
    noNotifications: 'No notifications',
    unread: 'Unread',
    allChannels: 'All channels',
    readAll: 'All read',
    deleteNotification: 'Delete',
    recentActivity: 'Recent activity',
    quickActions: 'Quick actions',
    viewAll: 'View all',
    backToAccounts: '← Back to accounts',
    backToCards: '← Cards',
    backToTransactions: '← Transactions',
    activate: 'Activate',
    resume: 'Resume',
    pause: 'Pause',
    next: 'Next',
    prev: 'Previous',
    page: 'Page',
    of: 'of',
    confirm: 'Confirm',
    warning: 'Warning',
  },
  bg: {
    signIn: 'Вход',
    welcomeBack: 'Добре дошли',
    dashboard: 'Табло',
    accounts: 'Сметки',
    cards: 'Карти',
    notifications: 'Известия',
    settings: 'Настройки',
    transfer: 'Превод',
    cardPayment: 'Картово плащане',
    transactions: 'Транзакции',
    scheduled: 'Планирани',
    openAccount: 'Откриване на сметка',
    current: 'Разплащателна',
    savings: 'Спестовна',
    business: 'Бизнес',
    available: 'Налично',
    blocked: 'Блокирано',
    total: 'Общо',
    from: 'От',
    to: 'Към',
    amount: 'Сума',
    description: 'Основание',
    cancel: 'Отказ',
    save: 'Запази',
    loading: 'Зареждане…',
    tryAgain: 'Опитай отново',
    noAccountsYet: 'Все още няма сметки',
    noCardsYet: 'Все още няма карти',
    noTxnsYet: 'Все още няма транзакции',
    markAllRead: 'Маркирай всички като прочетени',
    freeze: 'Замрази сметката',
    close: 'Закрий сметката',
    blockCard: 'Блокирай',
    terminate: 'Прекрати',
    saveChanges: 'Запази',
    issueCard: 'Издай карта',
    signOut: 'Изход',
    profile: 'Профил',
    language: 'Език',
    sessions: 'Сесии',
    password: 'Парола',
    username: 'Потребителско име',
    email: 'Имейл',
    phone: 'Телефон',
    firstName: 'Собствено',
    secondName: 'Бащино',
    thirdName: 'Фамилия',
    egn: 'ЕГН',
    birthDate: 'Дата на раждане',
    register: 'Създай профил',
    confirmPassword: 'Потвърди парола',
    security: 'Сигурност',
    twoFA: 'Двуфакторна автентикация',
    enable: 'Активирай',
    disable: 'Деактивирай',
    admin: 'Админ',
    send: 'Изпрати',
    broadcast: 'Масово',
    bulk: 'До група',
    users: 'Потребители',
    role: 'Роля',
    frequency: 'Честота',
    once: 'Еднократно',
    daily: 'Ежедневно',
    weekly: 'Седмично',
    monthly: 'Месечно',
    newScheduled: 'Ново планирано плащане',
    cardType: 'Вид карта',
    debit: 'Дебитна',
    credit: 'Кредитна',
    virtual: 'Виртуална',
    limits: 'Лимити',
    dailyLimit: 'Дневен лимит',
    monthlyLimit: 'Месечен лимит',
    singleLimit: 'Единична трансакция',
    branch: 'Клон',
    currency: 'Валута',
    balance: 'Баланс',
    iban: 'IBAN',
    status: 'Статус',
    type: 'Тип',
    date: 'Дата',
    reference: 'Референция',
    merchant: 'Търговец',
    noNotifications: 'Няма известия',
    unread: 'Непрочетени',
    allChannels: 'Всички канали',
    readAll: 'Всички прочетени',
    deleteNotification: 'Изтрий',
    recentActivity: 'Последна активност',
    quickActions: 'Бързи действия',
    viewAll: 'Виж всички',
    backToAccounts: '← Към сметките',
    backToCards: '← Карти',
    backToTransactions: '← Транзакции',
    activate: 'Активирай',
    resume: 'Продължи',
    pause: 'Спри',
    next: 'Следваща',
    prev: 'Предишна',
    page: 'Страница',
    of: 'от',
    confirm: 'Потвърди',
    warning: 'Внимание',
  }
};

type Lang = 'en' | 'bg';
type TranslationKey = keyof typeof translations.en;
type Translations = typeof translations.en;

interface LangContextValue {
  lang: Lang;
  setLang: (lang: Lang) => void;
  t: Translations;
}

export const LangContext = createContext<LangContextValue>({
  lang: 'en',
  setLang: () => {},
  t: translations.en,
});

export function LangProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Lang>(() => {
    const stored = localStorage.getItem('lang');
    return (stored === 'bg' ? 'bg' : 'en') as Lang;
  });

  const setLang = (newLang: Lang) => {
    localStorage.setItem('lang', newLang);
    setLangState(newLang);
  };

  return (
    <LangContext.Provider value={{ lang, setLang, t: translations[lang] }}>
      {children}
    </LangContext.Provider>
  );
}
